# Generated by Django 4.2.30 on 2026-07-06 00:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatBot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.CharField(max_length=2000, verbose_name='prompt')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
            ],
            options={
                'verbose_name': 'chatbot',
                'verbose_name_plural': 'chatbots',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='título')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('chatbot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='website.chatbot', verbose_name='chatbot')),
            ],
            options={
                'verbose_name': 'conversa',
                'verbose_name_plural': 'conversas',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='nome')),
            ],
            options={
                'verbose_name': 'curso',
                'verbose_name_plural': 'cursos',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='nome')),
                ('ra', models.CharField(max_length=50, unique=True, verbose_name='RA')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='telefone')),
                ('courses', models.ManyToManyField(blank=True, related_name='students', to='website.course', verbose_name='cursos')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
            ],
            options={
                'verbose_name': 'aluno',
                'verbose_name_plural': 'alunos',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='nome')),
                ('siape', models.CharField(max_length=50, unique=True, verbose_name='SIAPE')),
                ('courses', models.ManyToManyField(blank=True, related_name='professors', to='website.course', verbose_name='cursos')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='professor_profile', to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
            ],
            options={
                'verbose_name': 'professor',
                'verbose_name_plural': 'professores',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'Usuário'), ('assistant', 'Assistente')], max_length=20, verbose_name='papel')),
                ('content', models.TextField(verbose_name='conteúdo')),
                ('sources', models.JSONField(blank=True, default=list, verbose_name='fontes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='website.conversation', verbose_name='conversa')),
            ],
            options={
                'verbose_name': 'mensagem',
                'verbose_name_plural': 'mensagens',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='título')),
                ('text_content', models.TextField(blank=True, verbose_name='texto para busca')),
                ('file', models.FileField(blank=True, upload_to='materiais/%Y/%m/', verbose_name='arquivo')),
                ('public', models.BooleanField(default=True, verbose_name='tornar público')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('courses', models.ManyToManyField(blank=True, related_name='materials', to='website.course', verbose_name='cursos')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='website.professor', verbose_name='professor')),
            ],
            options={
                'verbose_name': 'material',
                'verbose_name_plural': 'materiais',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddField(
            model_name='conversation',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='website.student', verbose_name='aluno'),
        ),
        migrations.AddField(
            model_name='chatbot',
            name='courses',
            field=models.ManyToManyField(blank=True, related_name='chatbots', to='website.course', verbose_name='cursos'),
        ),
        migrations.AddField(
            model_name='chatbot',
            name='materials',
            field=models.ManyToManyField(blank=True, related_name='chatbots', to='website.material', verbose_name='materiais'),
        ),
        migrations.AddField(
            model_name='chatbot',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chatbots', to='website.professor', verbose_name='professor'),
        ),
    ]
