# Generated by Django 4.2.30 on 2026-07-06 00:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='model_name',
            field=models.CharField(blank=True, max_length=120, verbose_name='modelo'),
        ),
        migrations.AddField(
            model_name='message',
            name='provider',
            field=models.CharField(blank=True, max_length=20, verbose_name='provedor'),
        ),
        migrations.AddField(
            model_name='message',
            name='tokens_cached',
            field=models.PositiveIntegerField(default=0, verbose_name='tokens em cache'),
        ),
        migrations.AddField(
            model_name='message',
            name='tokens_completion',
            field=models.PositiveIntegerField(default=0, verbose_name='tokens de saída'),
        ),
        migrations.AddField(
            model_name='message',
            name='tokens_prompt',
            field=models.PositiveIntegerField(default=0, verbose_name='tokens de entrada'),
        ),
        migrations.AddField(
            model_name='message',
            name='tokens_total',
            field=models.PositiveIntegerField(default=0, verbose_name='tokens totais'),
        ),
        migrations.CreateModel(
            name='ProfessorConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(blank=True, choices=[('gemini', 'Google Gemini'), ('openrouter', 'OpenRouter')], max_length=20, verbose_name='provedor')),
                ('api_key', models.CharField(blank=True, max_length=255, verbose_name='chave da API')),
                ('model', models.CharField(blank=True, max_length=120, verbose_name='modelo')),
                ('token_limit_per_student', models.PositiveIntegerField(default=0, help_text='0 = ilimitado.', verbose_name='limite de tokens por aluno')),
                ('limit_period_days', models.PositiveIntegerField(default=0, help_text='0 = acumulado total (sem reinício).', verbose_name='período do limite (dias)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('professor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='config', to='website.professor', verbose_name='professor')),
            ],
            options={
                'verbose_name': 'configuração do professor',
                'verbose_name_plural': 'configurações dos professores',
            },
        ),
    ]
