# Generated by Django 6.0.5 on 2026-09-27 03:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_message_model_name_message_provider_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='category',
            field=models.CharField(choices=[('geral', 'Geral'), ('calendario', 'Calendário Acadêmico'), ('atividades_complementares', 'Atividades Complementares'), ('edital', 'Edital'), ('regulamento', 'Regulamento'), ('manual', 'Manual / Guia'), ('outro', 'Outro')], db_index=True, default='geral', max_length=50, verbose_name='categoria'),
        ),
        migrations.AddField(
            model_name='material',
            name='content_hash',
            field=models.CharField(blank=True, max_length=64, verbose_name='hash do conteúdo'),
        ),
        migrations.AddField(
            model_name='material',
            name='document_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='número / edital'),
        ),
        migrations.AddField(
            model_name='material',
            name='document_year',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='ano do documento'),
        ),
        migrations.AddField(
            model_name='material',
            name='effective_end',
            field=models.DateField(blank=True, null=True, verbose_name='fim da vigência'),
        ),
        migrations.AddField(
            model_name='material',
            name='effective_start',
            field=models.DateField(blank=True, null=True, verbose_name='início da vigência'),
        ),
        migrations.AddField(
            model_name='material',
            name='extraction_error',
            field=models.TextField(blank=True, verbose_name='erro de extração'),
        ),
        migrations.AddField(
            model_name='material',
            name='extraction_status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('success', 'Sucesso'), ('empty', 'Texto vazio'), ('unsupported', 'Não suportado'), ('scanned', 'Possível documento escaneado'), ('error', 'Erro de extração')], default='pending', max_length=20, verbose_name='status da extração'),
        ),
        migrations.AddField(
            model_name='material',
            name='processing_version',
            field=models.PositiveIntegerField(default=1, verbose_name='versão de processamento'),
        ),
        migrations.AddField(
            model_name='material',
            name='rectified_material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rectifications', to='website.material', verbose_name='material retificado'),
        ),
        migrations.AddField(
            model_name='professorconfig',
            name='embedding_model',
            field=models.CharField(blank=True, help_text='Opcional. Ex.: text-embedding-004.', max_length=120, verbose_name='modelo de embedding'),
        ),
        migrations.AddField(
            model_name='professorconfig',
            name='rag_mode',
            field=models.CharField(choices=[('two_stage', 'Duas etapas (Roteador + Gerador)'), ('direct', 'RAG Direto (Apenas Gerador)'), ('baseline', 'Baseline (Prefixos longos)')], default='two_stage', help_text='Estratégia de recuperação e geração.', max_length=20, verbose_name='modo RAG'),
        ),
        migrations.AddField(
            model_name='professorconfig',
            name='router_model',
            field=models.CharField(blank=True, help_text='Opcional. Se vazio, reutiliza o modelo principal.', max_length=120, verbose_name='modelo roteador'),
        ),
        migrations.CreateModel(
            name='LLMCallLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('router', 'Roteador / Classificador'), ('generator', 'Gerador de Resposta'), ('embedding', 'Embedding Vetorial')], max_length=20, verbose_name='etapa')),
                ('provider', models.CharField(blank=True, max_length=20, verbose_name='provedor')),
                ('model_name', models.CharField(blank=True, max_length=120, verbose_name='modelo')),
                ('status', models.CharField(choices=[('success', 'Sucesso'), ('failed', 'Falha'), ('fallback', 'Fallback')], default='success', max_length=20, verbose_name='status')),
                ('duration_ms', models.PositiveIntegerField(default=0, verbose_name='duração (ms)')),
                ('tokens_prompt', models.PositiveIntegerField(default=0, verbose_name='tokens de entrada')),
                ('tokens_completion', models.PositiveIntegerField(default=0, verbose_name='tokens de saída')),
                ('tokens_total', models.PositiveIntegerField(default=0, verbose_name='tokens totais')),
                ('tokens_cached', models.PositiveIntegerField(default=0, verbose_name='tokens em cache')),
                ('cost', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='custo')),
                ('currency', models.CharField(default='USD', max_length=10, verbose_name='moeda')),
                ('error_message', models.TextField(blank=True, verbose_name='mensagem de erro')),
                ('request_id', models.CharField(blank=True, db_index=True, max_length=64, verbose_name='id da requisição')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('chatbot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='llm_calls', to='website.chatbot', verbose_name='chatbot')),
                ('conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='call_logs', to='website.conversation', verbose_name='conversa')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='llm_calls', to='website.professor', verbose_name='professor')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='llm_calls', to='website.student', verbose_name='aluno')),
            ],
            options={
                'verbose_name': 'registro de chamada LLM',
                'verbose_name_plural': 'registros de chamadas LLM',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MaterialChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk_index', models.PositiveIntegerField(verbose_name='índice do chunk')),
                ('content', models.TextField(verbose_name='conteúdo do chunk')),
                ('page_or_section', models.CharField(blank=True, max_length=100, verbose_name='página ou seção')),
                ('token_count', models.PositiveIntegerField(default=0, verbose_name='contagem de tokens')),
                ('char_start', models.PositiveIntegerField(default=0, verbose_name='caractere inicial')),
                ('char_end', models.PositiveIntegerField(default=0, verbose_name='caractere final')),
                ('content_hash', models.CharField(blank=True, max_length=64, verbose_name='hash do chunk')),
                ('embedding_vector', models.JSONField(blank=True, null=True, verbose_name='vetor de embedding')),
                ('embedding_model', models.CharField(blank=True, max_length=120, verbose_name='modelo de embedding')),
                ('embedding_dimension', models.PositiveIntegerField(blank=True, null=True, verbose_name='dimensão do embedding')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='website.material', verbose_name='material')),
            ],
            options={
                'verbose_name': 'trecho de material',
                'verbose_name_plural': 'trechos de materiais',
                'ordering': ['chunk_index'],
                'unique_together': {('material', 'chunk_index')},
            },
        ),
    ]
